
# redis-cli -a redis --cluster create 172.16.238.11:6379 172.16.238.12:6379 172.16.238.13:6379 172.16.238.14:6379 172.16.238.15:6379 172.16.238.16:6379 --cluster-replicas 1
version: '3.3'
services:
  # 节点1
  redis1:
    # 启动之后的容器名称
    container_name: redis-master-1
    env_file: 
      # 环境配置
      - ./.env
    # 使用哪种镜像
    image: 'harbor.ubtrobot.com/database/redis:5.0.7'
    # 端口映射
    ports:
      - ${redis1_ports}
      - ${redis1_cluster}
    networks:
        cluster-net:
          ipv4_address: 172.16.238.11
    volumes:
      # 容器的data映射到宿主机
      - ./node-${redis1_port}/data:/data
      # 加载配置文件
      - ./node-${redis1_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件
    command: redis-server /usr/local/etc/redis/redis.conf
    environment: 
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点2
  redis2:
    container_name: redis-master-2
    env_file: 
      - ./.env
    # 使用哪种镜像
    image: 'harbor.ubtrobot.com/database/redis:5.0.7'
    # 端口映射
    ports:
      - ${redis2_ports}
      - ${redis2_cluster}
    networks:
        cluster-net:
          ipv4_address: 172.16.238.12
    volumes:
      # 容器的data映射到宿主机
      - ./node-${redis2_port}/data:/data
      # 加载配置文件
      - ./node-${redis2_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件  
    command: redis-server /usr/local/etc/redis/redis.conf
    environment: 
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点3
  redis3:
    container_name: redis-master-3
    env_file:
      - ./.env
    # 使用哪种镜像
    image: 'harbor.ubtrobot.com/database/redis:5.0.7'
    # 端口映射
    ports:
      - ${redis3_ports}
      - ${redis3_cluster}
    networks:
        cluster-net:
          ipv4_address: 172.16.238.13
    volumes:
      # 容器的data映射到宿主机
      - ./node-${redis3_port}/data:/data
      # 加载配置文件
      - ./node-${redis3_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点4
  redis4:
    container_name: redis-slave-1
    env_file:
      - ./.env
    # 使用哪种镜像
    image: 'harbor.ubtrobot.com/database/redis:5.0.7'
    # 端口映射
    ports:
      - ${redis4_ports}
      - ${redis4_cluster}
    networks:
        cluster-net:
          ipv4_address: 172.16.238.14
    volumes:
      # 容器的data映射到宿主机
      - ./node-${redis4_port}/data:/data
      # 加载配置文件
      - ./node-${redis4_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点5
  redis5:
    container_name: redis-slave-2
    env_file:
      - ./.env
    # 使用哪种镜像
    image: 'harbor.ubtrobot.com/database/redis:5.0.7'
    # 端口映射
    ports:
      - ${redis5_ports}
      - ${redis5_cluster}
    networks:
        cluster-net:
          ipv4_address: 172.16.238.15
    volumes:
      # 容器的data映射到宿主机
      - ./node-${redis5_port}/data:/data
      # 加载配置文件
      - ./node-${redis5_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点6
  redis6:
    container_name: redis-slave-3
    env_file:
      - ./.env
    # 使用哪种镜像
    image: 'harbor.ubtrobot.com/database/redis:5.0.7'
    # 端口映射
    ports:
      - ${redis6_ports}
      - ${redis6_cluster}
    networks:
        cluster-net:
          ipv4_address: 172.16.238.16
    volumes:
      # 容器的data映射到宿主机
      - ./node-${redis6_port}/data:/data
      # 加载配置文件
      - ./node-${redis6_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  sentinel-9001:
    container_name: sentinel-9001
    image: 'harbor.ubtrobot.com/database/redis:5.0.7'
    ports:
      - 26379:26379
    networks:
        cluster-net:
          ipv4_address: 172.16.238.240
    volumes:
      - ./sentinel-9001/data:/data
      - ./sentinel-9001/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel

  sentinel-9002:
    container_name: sentinel-9002
    image: 'harbor.ubtrobot.com/database/redis:5.0.7'
    ports:
      - 26380:26379
    networks:
        cluster-net:
          ipv4_address: 172.16.238.241
    volumes:
      - ./sentinel-9002/data:/data
      - ./sentinel-9002/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel

  sentinel-9003:
    container_name: sentinel-9003
    image: 'harbor.ubtrobot.com/database/redis:5.0.7'
    ports:
      - 26381:26379
    networks:
        cluster-net:
          ipv4_address: 172.16.238.242
    volumes:
      - ./sentinel-9003/data:/data
      - ./sentinel-9003/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel
networks:
  # 创建集群网络，在容器之间通信
  cluster-net:
    ipam:
      config:
        - subnet: 172.16.238.0/24
